###########################################################
# Global Configuration (https://jekyllrb.com/docs/configuration/options/)
###########################################################
# if you want to force HTTPS, specify the domain without the http at the start
# set domain: "your_github_user_name.github.io"
# for GitHub Pages, url: "https://your_github_user_name.github.io"
# if your page is located at https://your_github_user_name.github.io/blog, then set baseurl: "/blog"
domain: ""
url: ""
baseurl: ""

# please use TZ database name column on the list table https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: "US/Pacific"

###########################################################
# Front Matter Defaults (https://jekyllrb.com/docs/configuration/front-matter-defaults/)
###########################################################
defaults:
  # for posts
  - scope:
      # to separate language posts folders
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:path

  # example: enable setting for all pages. You may still need to enable some setting from _data/conf/posts.yml or _data/conf/main.yml
  # - scope:
  #     # an empty string here means all files in the project
  #     path: ""
  #   values:
  #     image_viewer_on: true
  #     image_lazy_loader_on: true

###########################################################
# Markdown Options (https://jekyllrb.com/docs/configuration/markdown/)
# Configuring Jekyll in your GitHub Pages site (https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll)
###########################################################
# This is default for GitHub Pages sites and cannot be changed.
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge # This is default for GitHub Pages sites and cannot be changed.

###########################################################
# Plugins (Plugins supported by GitHub Pages https://pages.github.com/versions/)
# since GitHub Pages runs jekyll with "--safe" flag, we need to add supported plugins in here. (only github supported plugins are allowed)
###########################################################
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-paginate
  - jekyll-redirect-from

###########################################################
# jekyll-paginate (https://jekyllrb.com/docs/pagination/)
# make sure this matches with post_query_paginator_post_per_page in _data/conf/posts.yml
###########################################################
paginate_path: "/tabs/blog/:num"
paginate: 5 # number of post per page

###########################################################
# jekyll-redirect-from (https://github.com/jekyll/jekyll-redirect-from)
###########################################################
redirect_from:
  # Disabling generation of redirects.json
  json: false

###########################################################
# html compression (https://jch.penibelst.de)
###########################################################
compress_html:
  clippings: all
  comments: all
  #endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development] # disable this feature for development env.

###########################################################
# js compression (for removing comments(/**/only), line breaks and spaces)
# for debugging js files, simply set linebreak_and_space: false (in production env, this will be enabled automatically)
# for more info about environments (https://jekyllrb.com/docs/configuration/environments/)
###########################################################
compress_js:
  linebreak_and_space: false # enable or disable line breaks and space removal feature for development env.
  ignore: development # disable this feature entirely for development or production env.

###########################################################
# Sass (https://jekyllrb.com/docs/assets/)
# enable css compression
###########################################################
sass:
  sass_dir: assets/_scss
  style: compressed

###########################################################
# Exclude these files or folders from production site
###########################################################
exclude: ["Gemfile*", "vendor", ".github", ".vscode", "README*", "CODE_OF_CONDUCT.md", "LICENSE", "docs"]
